# Generated by Django 3.1.4 on 2020-12-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vechile_name', models.CharField(max_length=200)),
                ('vechile_series', models.CharField(max_length=200)),
                ('vechile_price', models.IntegerField()),
                ('vechile_description', models.TextField()),
                ('vechile_image', models.CharField(default='https://www.google.com/search?q=coming+soon+images&tbm=isch&source=iu&ictx=1&fir=c9EY_13CZrZRWM%252CZL4qJNgKW_3MbM%252C_&vet=1&usg=AI4_-kSNigLBzBYkcLD6F8TsMbtt0ISAKA&sa=X&ved=2ahUKEwi5zb_fgNjtAhVaxDgGHXYyA24Q9QF6BAgNEAE#imgrc=c9EY_13CZrZRWM', max_length=500)),
            ],
        ),
    ]
