# Generated by Django 3.1.4 on 2020-12-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='poject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_price', models.IntegerField()),
                ('project_author', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
            ],
        ),
    ]
