# Generated by Django 3.1.4 on 2020-12-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poject',
            name='project_author_mail_id',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='poject',
            name='project_id',
            field=models.IntegerField(default='null'),
        ),
        migrations.AddField(
            model_name='poject',
            name='project_img',
            field=models.CharField(default='https://glch.org.au/wp-content/uploads/2015/09/Coming-Soon-1024x1024.jpg', max_length=500),
        ),
    ]
