# Generated by Django 3.1.4 on 2020-12-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_project', '0002_auto_20201216_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poject',
            name='project_id',
            field=models.IntegerField(default=0),
        ),
    ]
