# Generated by Django 3.1.4 on 2020-12-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_project', '0006_remove_poject_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='poject',
            name='project_id',
            field=models.IntegerField(default=1),
        ),
    ]
