# Generated by Django 3.1.4 on 2020-12-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_project', '0007_poject_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poject',
            name='project_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
