# Generated by Django 3.1.4 on 2020-12-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clg_project', '0008_auto_20201216_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poject',
            name='project_author_mail_id',
        ),
        migrations.RemoveField(
            model_name='poject',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='poject',
            name='project_img',
        ),
    ]
