# Generated by Django 3.1.4 on 2020-12-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_project', '0009_auto_20201216_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='poject',
            name='project_image',
            field=models.CharField(default='https://th.bing.com/th/id/OIP.WcPTltgdtoFyOmeQHPsEvgHaHa?pid=Api&rs=1', max_length=500),
        ),
    ]
