# Generated by Django 3.1.6 on 2021-02-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_employee_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
